# Generated by Django 3.2.25 on 2024-09-14 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Church_Event_Register',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_title', models.CharField(max_length=64)),
                ('event_description', models.CharField(max_length=64)),
                ('event_date', models.CharField(max_length=64)),
                ('event_time', models.CharField(max_length=64)),
                ('location', models.CharField(max_length=64)),
                ('targeted_group', models.CharField(max_length=64)),
                ('pastor_in_charge', models.CharField(max_length=64)),
                ('phone_number', models.CharField(max_length=64)),
                ('is_the_event_approved', models.CharField(max_length=64)),
                ('approved_by', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Church_Service',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('date', models.CharField(max_length=64)),
                ('opening_time', models.CharField(max_length=64)),
                ('nature_of_service', models.CharField(max_length=64)),
                ('topic_of_sermon', models.CharField(max_length=64)),
                ('scripture_reading', models.CharField(max_length=64)),
                ('preacher', models.CharField(max_length=64)),
                ('closing_time', models.CharField(max_length=64)),
                ('men_attendance', models.CharField(max_length=64)),
                ('women_attendance', models.CharField(max_length=64)),
                ('tithes', models.CharField(max_length=64)),
                ('offering', models.CharField(max_length=64)),
                ('seed_offering', models.CharField(max_length=64)),
                ('building_offering', models.CharField(max_length=64)),
                ('welfare_offering', models.CharField(max_length=64)),
                ('thanksgiving_offering', models.CharField(max_length=64)),
                ('other_offerings', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='First_Timer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('visitors_name', models.CharField(max_length=64)),
                ('who_invited_you', models.CharField(max_length=64)),
                ('phone_number', models.CharField(max_length=64)),
                ('email_address', models.CharField(max_length=64)),
                ('purpose_of_coming', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=64)),
                ('sex', models.CharField(max_length=64)),
                ('marital_status', models.CharField(max_length=64)),
                ('would_you_like_to_be_our_member', models.CharField(max_length=64)),
                ('your_experience_in_the_service', models.CharField(max_length=64)),
                ('have_you_given_your_life_to_christ', models.CharField(max_length=64)),
                ('if_yes_date_converted', models.CharField(max_length=64)),
                ('your_prayer_request', models.CharField(max_length=64)),
                ('will_you_like_to_fellowship_with_us_again', models.CharField(max_length=64)),
                ('record_officer', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=64)),
                ('sex', models.CharField(max_length=64)),
                ('dob', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=64)),
                ('office_address', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=64)),
                ('marital_status', models.CharField(max_length=64)),
                ('spouse_name', models.CharField(max_length=64)),
                ('number_of_children', models.CharField(max_length=64)),
                ('occupation', models.CharField(max_length=64)),
                ('date_joined_church', models.CharField(max_length=64)),
                ('membership_status', models.CharField(max_length=64)),
                ('date_of_conversion', models.CharField(max_length=64)),
                ('baptism_date', models.CharField(max_length=64)),
            ],
        ),
    ]
