# Generated by Django 3.2.25 on 2024-09-14 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Church', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=200)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Facility_Management',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('facility_name', models.CharField(max_length=64)),
                ('facility_type', models.CharField(max_length=64)),
                ('facility_location', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=64)),
                ('maintenance_log', models.CharField(max_length=64)),
                ('last_date_maintained', models.CharField(max_length=64)),
                ('next_due_date', models.CharField(max_length=64)),
                ('maintenance_expense', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=200)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=64)),
                ('quantity', models.CharField(max_length=64)),
                ('status', models.CharField(max_length=64)),
                ('other_info', models.CharField(max_length=64)),
                ('record_officer', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Order_Of_Service',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nature_of_service', models.CharField(max_length=64)),
                ('activities', models.CharField(max_length=64)),
                ('duration', models.CharField(max_length=64)),
                ('activities_moderator', models.CharField(max_length=64)),
                ('service_time', models.CharField(max_length=64)),
                ('service_cordinator', models.CharField(max_length=64)),
                ('service_date', models.CharField(max_length=64)),
            ],
        ),
    ]
