# Generated by Django 3.2.25 on 2024-09-15 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Church', '0003_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Churcharm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('party', models.CharField(blank=True, default='Test', max_length=50, null=True)),
                ('members', models.ManyToManyField(to='Church.Members')),
            ],
        ),
    ]
