# Generated by Django 3.2.25 on 2024-09-15 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Church', '0004_churcharm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='churcharm',
            name='party',
        ),
        migrations.RemoveField(
            model_name='department',
            name='party',
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('gross', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('net', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Church.members')),
            ],
        ),
    ]
