# Generated by Django 3.2.25 on 2024-09-15 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Church', '0006_auto_20240915_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
