# Generated by Django 3.2.25 on 2024-09-15 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Church', '0007_alter_payroll_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='tax',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
